name: "Delta Chat YT Bot"
description: "Downloads video and music via yt-dlp, slices tracks, and supports Yandex Music, SoundCloud, VK, and Navidrome"
version: "1.6.54"
slug: "deltachat_yt"
url: "https://github.com/mrgluek/deltachat_yt"
arch:
  - aarch64
  - amd64
image: "ghcr.io/mrgluek/addon-deltachat-yt"
startup: "services"
boot: "auto"
init: true
options:
  chatmail_qr: ""
  email: ""
  password: ""
  mail_server: ""
  mail_port: 993
  send_server: ""
  send_port: 465
  admin_email: ""
  admin_fingerprint: ""
  display_name: "YT Bot"
  status_text: "Downloads media, audio and music via Delta Chat"
schema:
  chatmail_qr: "str?"
  email: "str?"
  password: "password?"
  mail_server: "str?"
  mail_port: "int?"
  send_server: "str?"
  send_port: "int?"
  admin_email: "str?"
  admin_fingerprint: "str?"
  display_name: "str?"
  status_text: "str?"
