name: "Delta Chat Bouncer Bot"
description: "Anti-spam protection, message auto-responder, contact whitelist filter, and forwarder for Delta Chat"
version: "2.8.1"
slug: "deltachat_bouncer"
url: "https://github.com/mrgluek/deltachat_bouncer"
arch:
  - aarch64
  - amd64
image: "ghcr.io/mrgluek/addon-deltachat-bouncer"
startup: "services"
boot: "auto"
init: true
options:
  chatmail_qr: ""
  email: ""
  password: ""
  mail_server: ""
  mail_port: 993
  send_server: ""
  send_port: 465
  admin_email: ""
  admin_fingerprint: ""
  display_name: "Bouncer Bot"
  status_text: "Guards and bounces unwanted messages"
schema:
  chatmail_qr: "str?"
  email: "str?"
  password: "password?"
  mail_server: "str?"
  mail_port: "int?"
  send_server: "str?"
  send_port: "int?"
  admin_email: "str?"
  admin_fingerprint: "str?"
  display_name: "str?"
  status_text: "str?"
